### ISSUE TITLE
Cannot start with npm run start:prod

### ISSUE THREAD

**Issue by grigori-gru** [nestjs/nest#2599]
## Current behavior
Exit with error:
```
node_modules/@nestjs/core/application-config.d.ts:2:39 - error TS2307: Cannot find module '@nestjs/common/interfaces/configuration-provider.interface'.

2 import { ConfigurationProvider } from '@nestjs/common/interfaces/configuration-provider.interface';
```
## Input Code
My scripts in starting prod:
```
"build": "tsc -p tsconfig.build.json",
"prestart:prod": "rimraf dist && npm run build",
 "start:prod": "NODE_ENV=production node dist/main.js",
```
All worked with nest/common 6.2.3
## Expected behavior
All works correct in dev and test starting: 
```
"start:dev": "NODE_ENV=dev LOG_LEVEL=FINE nodemon",
"test": "jest --runInBand --detectOpenHandles --forceExit",
```

And all works with 
## Possible Solution
I tried to update to 6.5.2 core version but my Jwt Auth has been failed with:
```
Nest can't resolve dependencies of the JwtStrategy (AuthService, ?)
```
 i can't fix this. It's not about this issue.

## Environment
"@nestjs/common": "^6.5.2",
"@nestjs/core": "^6.2.3",

For Tooling issues:
- Node version: 11.7.0
- Platform:  Linux 

Others:

</code></pre>

**Comment by caiognecco** [comment]
Try, if it's possible, to update your @nestjs/core:

npm i --save @nestjs/core@latest

regards

**Comment by kamilmysliwiec** [comment]
```
"@nestjs/common": "^6.5.2",
"@nestjs/core": "^6.2.3",
```

You shouldn't have different versions of these packages. Either downgrade `@nestjs/common` or upgrade `@nestjs/core` to the latest version. 

```
Nest can't resolve dependencies of the JwtStrategy (AuthService, ?)
```

Just ensure that 2nd dependency of `JwtStrategy` is available in the scope in which you want to use this class.

**Comment by seniorpreacher** [comment]
I had experienced the same behaviour on my `start:dev` script.

`npm i --save @nestjs/core@latest` fixed it for me too ;)

**Comment by Gesh4o** [comment]
I experienced this issue after running 'npm audit fix' which ultimately changed "@nestjs/common" and "@nestjs/core" to different versions as described above.
