### ISSUE TITLE
linux build Error

### ISSUE THREAD

**Issue by LLLLLamHo** [nestjs/nest#3622]
## Current behavior
I am running nest build command in centos of Linux system, but I Cannot find module
![image](https://user-images.githubusercontent.com/19260349/70614271-29ede880-1c45-11ea-9a4a-1579e476e9e8.png)
But I run it on my MAC and it compiles。

"@nestjs/common": "6.7.2",
"@nestjs/core": "6.7.2",
"@nestjs/cli": "6.9.0",

## Expected behavior
Can compile normally under Linux

## Environment

<pre><code>
Nest version: 6.7.2
 
For Tooling issues:
- Node version: v8.14.0
- Platform:  Linux

**Comment by kamilmysliwiec** [comment]
You have different versions of the `@nestjs/cli` installed globally. Ensure to update them to the latest versions.

**Comment by LLLLLamHo** [comment]
The same problem occurred when I upgraded the cli to 6.12.9

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
