### ISSUE TITLE
Cannot find name 'WebSocket'

### ISSUE THREAD

**Issue by mmenik** [nestjs/nest#838]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
When I compile with tsc I get the following error:

node_modules/@nestjs/websockets/adapters/ws-adapter.d.ts(16,33): error TS2304: Cannot find name 'WebSocket'

I look how to solve it in other issues via @types/socket.io but don't work

## Environment

<pre><code>
Nest version: 5.0.1
Nest Websockets: 5.0.1
@types/socket.io: 1.4.36

 
For Tooling issues:
- Node version: 9.11.1
- Platform:  Linux Ubuntu

Others:

</code></pre>

**Comment by cojack** [comment]
@mmenik without code it's impossible to solve your problem

**Comment by mmenik** [comment]
The problem is inside the websockets package of nestjs, all typescript code that use @nestjs/websockets when it's compiled with tpc go to error, if i use for esample nodemon with ts-node the error not occurred

**Comment by mmenik** [comment]
Yes

"@types/node": "^9.3.0"

I tried too set in tsconfig.json compiler options target to es2017

**Comment by kamilmysliwiec** [comment]
Let's try to update Nest to `v5.1.0`

**Comment by cojack** [comment]
@mmenik many times I end up with `"socket.io": "^2.1.1",` in package.json, try that and before, update nest :+1:

**Comment by mmenik** [comment]
Great after updated to v5.1.0 work fine
