### ISSUE TITLE
request property in a service class is undefined after v9.3.1

### ISSUE THREAD

**Issue by karam-mustafa** [nestjs/nest#11002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a simple constrictor for a service class as following

` constructor(
    @Inject(REQUEST) public readonly request: Request,
    runAuthDependincies: Boolean = true,
  )`
  
  after you had released v9.3.1 this request is undefined

### Minimum reproduction code
https://codesandbox.io/s/withered-monad-zgg1nu
-

### Steps to reproduce

just updating the packages to 9.3.1

### Expected behavior

The request property should not be undefined as before

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.3.1

### Packages versions

```json
"@hapi/hapi": "^21.0.0",
        "@hapi/joi": "^17.1.1",
        "@nestjs-modules/mailer": "^1.8.1",
        "@nestjs/common": "^9.0.0",
        "@nestjs/config": "^2.2.0",
        "@nestjs/core": "^9.0.0",
        "@nestjs/jwt": "^9.0.0",
        "@nestjs/passport": "^9.0.0",
        "@nestjs/platform-express": "^9.0.0",
        "apollo-server-express": "^3.11.1",
        "apollo-server-plugin-base": "^3.7.1",
        "class-transformer": "^0.5.1",
        "class-validator": "^0.13.2",
        "dotenv": "^16.0.3",
        "googleapis": "^109.0.1",
        "nodemailer": "^6.9.0",
        "passport-google-oauth20": "^2.0.0",
        "reflect-metadata": "^0.1.13",
        "rimraf": "^3.0.2",
        "rxjs": "^7.2.0"
```

### Node.js version

16.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
are you using durable providers?

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by micalevisk** [comment]
@karam-mustafa read this: https://github.com/nestjs/nest/pull/10809

**Comment by karam-mustafa** [comment]
> * are you using durable providers?
> * did you have some `ContextIdStrategy`? show us

here is my basic service class

```
import {
  google,
  Auth,
  GoogleApis,
  admin_directory_v1,
  drive_v3,
  drive_v2,
} from 'googleapis';

import { Request } from 'express';
import { Inject, Injectable, Scope } from '@nestjs/common';
import { REQUEST } from '@nestjs/core';

@Injectable({ scope: Scope.REQUEST })

export class BaseGoogleServices {
  requestProp: Request;

  constructor(
    @Inject(REQUEST) public readonly request: Request,
    runAuthDependincies: Boolean = true,
  ) {
       this.requestProp = request;
    }

    if (runAuthDependincies) {
      this.resolveAuthDependencies();
    }
  }

  resolveAuthDependencies() {
    // do some code
  }
}

```

**Comment by jmcdo29** [comment]
I'll say it one more time.

Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

Otherwise, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by karam-mustafa** [comment]
> I'll say it one more time.
> 
> Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
> 
> ## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
> Otherwise, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

https://codesandbox.io/s/withered-monad-zgg1nu

**Comment by jmcdo29** [comment]
Your reproduction doesn't start. `@nestjs/core` and `@nestjs/common` are missing and the web preview stays on a 502 bad gateway screen. Please don't make us do the work of fixing your reproduction just so we can see your bug.

**Comment by micalevisk** [comment]
![image](https://user-images.githubusercontent.com/13461315/216175762-87232e8b-be60-4ecb-807b-ec758c439c24.png)

I just tested your repro (after minor changes to make it minimal as possible while valid). Your repro doesn't reproduces the issue.

<details>
<summary>full code</summary>

```ts
// main.ts
import { NestFactory } from '@nestjs/core';
import type { NestExpressApplication } from '@nestjs/platform-express';
import { AppModule } from './app.module';
 
async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);
  await app.listen(process.env.PORT || 3000);
}
bootstrap();
```

```ts
import { Module, Controller, Get, Inject, Injectable, Scope } from '@nestjs/common';
import { REQUEST } from '@nestjs/core';
import { Request } from 'express';


@Injectable({ scope: Scope.REQUEST })
class Foo {
  constructor(
    @Inject(REQUEST) public readonly request: Request,
  ) {
    console.log('====================================');
    console.log(typeof request === 'undefined'); // false
    console.log('====================================');
  }
}


class AppService extends Foo {
  constructor(
    @Inject(REQUEST) public readonly request: Request,
  ) {
    super(request)
    console.log(typeof request === 'undefined'); // false
  }
}



@Controller()
class AppController {
  constructor(private readonly appService: AppService) {}
  @Get()
  getHello(): string {
    return 'ok'
  }
}



@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```


</details>

**Comment by karam-mustafa** [comment]
> Your reproduction doesn't start. `@nestjs/core` and `@nestjs/common` are missing and the web preview stays on a 502 bad gateway screen. Please don't make us do the work of fixing your reproduction just so we can see your bug.

Sorry for this confusion, I will let you know again when the repo could reproduce the issue, thanks for your patience

**Comment by davidzwa** [comment]
Having the same issue: 
- The request is undefined when accessing it from a service which is marked as `scope.REQUEST`
- After the 9.3.1 update this problem suddenly occurred
- I cant get it reproduced in CodeSandbox, which suggests to me another dependency in my module is causing this problem. I am not using durability.
https://codesandbox.io/p/sandbox/runtime-star-dpm9rv?file=%2Fsrc%2Fapp.module.ts&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A11%7D%5D

- I simplified the code of @karam-mustafa without gateway 502 error 
- Removed noise or unused packages irrelevant to the problem
- I updated and pinned all the packages to the latest versions (that I have locally as well)

Any tips on how I can help you refine this issue further from this point?

**Comment by kamilmysliwiec** [comment]
@micalevisk so I'm guessing this might be related to this PR https://github.com/nestjs/nest/pull/10809 (perhaps `isDependencyTreeDurable` returns true even though the tree isn't durable for some edge-case scenarios?

**Comment by Drugg0ff** [comment]
Same problem. Error when migrating from 9.2.1 to 9.3.1 - UnhandledPromiseRejectionWarning: TypeError: this.graphInspector.insertEntrypointDefinition is not a function

**Comment by micalevisk** [comment]
@Durairaj that's another one. Upgrade your `@nestjs/core` to 9.3

**Comment by micalevisk** [comment]
@kamilmysliwiec since no one shared any repro, I guess we can revert that PR for now.

**Comment by micalevisk** [comment]
hi @davidzwa is there any chance to share your code in a private repository with me?

or maybe you can see what was done at PR #10809 (which is pretty small) and try to debug it locally yourself :)

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/pull/11018

**Comment by davidzwa** [comment]
@micalevisk in the 9.2.1 edition neither MiddlewareModule::bindHandler or MiddlewareModule::registerHandler function is being called (no breakpoints or console logs that I added seem to trigger in the transpiled js code of nestjs).

Im not in the position to share the repo. Will keep you posted if I have more info to share.

**Comment by micalevisk** [comment]
@davidzwa another thing you could do: define the env var `NEST_DEBUG=true` and see if you got occurrence of 'durable' in your logs

**Comment by davidzwa** [comment]
That tip is really nice! I think this extract might help you:

```
[server-nest] Info      02/02/2023, 17:06:17 [InstanceWrapper] PrinterController introspected as request-scoped - {} +0ms
[server-nest] Info      02/02/2023, 17:06:17 Starting server at port 4000 - {} +0ms
[server-nest] Info      02/02/2023, 17:06:17 [PrinterGateway] Gateway initialized - {} +1ms
[server-nest] Info      02/02/2023, 17:06:17 [WebSocketsController] PrinterGateway subscribed to the "init-request" message - {} +0ms
[server-nest] Info      02/02/2023, 17:06:17 [AdminGateway] SocketIO AdminUI enabled. This can be disabled with: 'SOCKETIO_ADMINUI_ENABLED=false' - {} +0ms
[server-nest] Info      02/02/2023, 17:06:17 [InstanceWrapper] PrinterController introspected as durable - {} +5ms
[server-nest] Info      02/02/2023, 17:06:17 [InstanceWrapper] PrinterFileController introspected as durable - {} +0ms
```

Before the listen call we see `PrinterController introspected as request-scoped`, immediately after the `listen(...)` call the logs show ` PrinterController introspected as durable`. This is the function that prints that (just making sure that I follow what is happening):
https://github.com/nestjs/nest/blob/a439cd9a4120526a95295691e1ebbbce95d64f90/packages/core/injector/instance-wrapper.ts#L255

**Comment by micalevisk** [comment]
great, thanks

now could you please remove the `!item.isDependencyTreeStatic()` condition  
from L121 `node_modules/@nestjs/core/injector/instance-wrapper.js`

https://github.com/nestjs/nest/blob/d9c394bb44711ba33cde8aa9199d9fdf21052d7e/packages/core/injector/instance-wrapper.ts#L215-L223

I'm suggesting this because that was another change introduced in 9.3.1 (PR #10698)

**Comment by micalevisk** [comment]
@kamilmysliwiec ok so here we go

Can we revert #10698 and then revert #11018 ?

**Comment by vizio360** [comment]
Right, will look at it as well as soon as I get some free time. Disappointed my first contribution broke stuff...

**Comment by vizio360** [comment]
just reading through the thread, @davidzwa the example on CodeSandbox does it break when you run it locally?

**Comment by micalevisk** [comment]
@vizio360 it doesn't

we have no repro so far

**Comment by vizio360** [comment]
@davidzwa could you check the dependencies chain of `PrinterFileController` and `PrinterController` and list them out?
What I'm interested in is the scopes of each injected dependency and their dependencies.

Hopefully you don't have too many :)

**Comment by SocketSomeone** [comment]
Any pipes with scope `REQUEST` doesnt work 👍🏻

**Comment by vizio360** [comment]
What is interesting is that from the log @davidzwa provided the `PrinterController` does get request scope initially (see first line of the log) and then it gets durable... 

```
[server-nest] Info      02/02/2023, 17:06:17 [InstanceWrapper] PrinterController introspected as request-scoped - {} +0ms
[server-nest] Info      02/02/2023, 17:06:17 Starting server at port 4000 - {} +0ms
[server-nest] Info      02/02/2023, 17:06:17 [PrinterGateway] Gateway initialized - {} +1ms
[server-nest] Info      02/02/2023, 17:06:17 [WebSocketsController] PrinterGateway subscribed to the "init-request" message - {} +0ms
[server-nest] Info      02/02/2023, 17:06:17 [AdminGateway] SocketIO AdminUI enabled. This can be disabled with: 'SOCKETIO_ADMINUI_ENABLED=false' - {} +0ms
[server-nest] Info      02/02/2023, 17:06:17 [InstanceWrapper] PrinterController introspected as durable - {} +5ms
[server-nest] Info      02/02/2023, 17:06:17 [InstanceWrapper] PrinterFileController introspected as durable - {} +0ms
```

**Comment by davidzwa** [comment]
I've done some really extensive digging/hacking (on my project, no NestJS internals) and removed almost everything from except for my printer controller and service. After that I went much further to delete almost everything that I could possibly delete or nullify.
Still left with the error.

```
[server-nest] Info      03/02/2023, 00:01:50 [InstanceWrapper] PrinterController introspected as request-scoped - {} +0ms
[server-nest] Info      03/02/2023, 00:01:50 Starting server at port undefined - {} +3ms
[server-nest] Info      03/02/2023, 00:01:50 [InstanceWrapper] PrinterController introspected as durable - {} +5ms
```

So far what I think is left is a TypeORM feature called Printer (entity), AutoMapper and the two-layer mixin extensions I use to provide the controller with CRUD operations.

- Controller => CrudController => ReadonlyCrudController 
- CrudService => ReadonlyCrudService
- AutoMapper
- TypeORM feature
- HttpModule

With a fresh mind I should be able to port this into CodeSandbox. Cant promise it tho. Hope this helps.

**Comment by vizio360** [comment]
@davidzwa to clarify you are not setting up Durable Providers with a `ContextidStrategy` right?

**Comment by davidzwa** [comment]
> @davidzwa to clarify you are not setting up Durable Providers with a `ContextidStrategy` right?

Indeed, none of my services (or anything) follow the durable provider pattern described by https://docs.nestjs.com/fundamentals/injection-scopes#durable-providers

All is purely transient, singleton or request scoped.

**Comment by davidzwa** [comment]
I found a hint towards the problem! :)
It is here:
`this.isTreeDurable = !isTreeNonDurable && this.durable !== false;`

In my case `this.durable === undefined`. How that is I have no idea, but it fails the check.

**Comment by vizio360** [comment]
mm that should be ok as the first `!isTreeNonDurable` should return false so the second should not even be considered

**Comment by davidzwa** [comment]
Removing AutoMapper has removed the problem.

**Comment by vizio360** [comment]
what does that pesky automapper do???? :)

**Comment by davidzwa** [comment]
Will attempt to repro this soon, if time allows.

**Comment by vizio360** [comment]
I'm a bit ignorant on AutoMapper, could you point me to its repo?

**Comment by micalevisk** [comment]
https://automapperts.netlify.app/

**Comment by davidzwa** [comment]
https://www.npmjs.com/package/@automapper/nestjs
https://github.com/nartc/mapper/tree/main

**Comment by davidzwa** [comment]
> this.durable === undefined

I still hope you agree that `this.durable !== false` should not result in true if there is clearly no durability. That's an edge case in my view.

**Comment by vizio360** [comment]
wondering if we could replace that with `this.isTreeDurable = !isTreeNonDurable && this.durable`

**Comment by kamilmysliwiec** [comment]
> Can we revert https://github.com/nestjs/nest/pull/10698 and then revert https://github.com/nestjs/nest/pull/11018 ?

https://github.com/nestjs/nest/pull/11018 reverted. Now - not sure what we should do about this one https://github.com/nestjs/nest/pull/10698 - sounds like this issue only occurs when AutoMapper is included in the project?

**Comment by vizio360** [comment]
@karam-mustafa are you also using AutoMapper?

**Comment by vizio360** [comment]
@davidzwa I managed to force the error caused by `this.durable !== false`. Repro repo here https://github.com/vizio360/nestJSDurableProvidersIssue/tree/nonExplicitDurability with description and instructions in the README file.

Will create an issue, even though this is tested on nestjs 9.3.1 and we still don't know if the PRs in there can be reapplied. I think it will depend on what we understand about the issue with AutoMapper.

**Comment by vizio360** [comment]
> > Can we revert #10698 and then revert #11018 ?
> 
> #11018 reverted. Now - not sure what we should do about this one #10698 - sounds like this issue only occurs when AutoMapper is included in the project?

@kamilmysliwiec I will try and get automapper in my repro repo, and see if I can figure out what the issue is.

**Comment by karam-mustafa** [comment]
> @karam-mustafa are you also using AutoMapper?

I didn't install it before

**Comment by micalevisk** [comment]
@karam-mustafa is it working now in v9.3.2 right?

**Comment by kamilmysliwiec** [comment]
@micalevisk note - I didn't revert https://github.com/nestjs/nest/pull/10698 yet

**Comment by vizio360** [comment]
@kamilmysliwiec @micalevisk just experienced the problem in our code base with nestjs 9.3.2 and we do not use AutoMapper.

**Comment by micalevisk** [comment]
that's expected as your PR wasn't reverted yet.

So now you have a reproduction of that bug that you can work with, right?

**Comment by vizio360** [comment]
> 

Correct, and we are not using `ContextIdStrategy`, so it sounds like the same issue @davidzwa is having.

**Comment by davidzwa** [comment]
Just pitching in shortly, I was using 2 Crud mixins in my controller. It was too late in the night for me to eliminate that as a cause

**Comment by vizio360** [comment]
@kamilmysliwiec @micalevisk so in 9.3.2 [11018](https://github.com/nestjs/nest/pull/11018) is out while [10698](https://github.com/nestjs/nest/pull/10698) is still included?

**Comment by micalevisk** [comment]
@vizio360 exactly. 9.3.2 doesn't fix the bug introduced in 9.3.0

**Comment by vizio360** [comment]
@davidzwa  ok, can you reintroduce AutoMapper and make this change `this.isTreeDurable = !isTreeNonDurable && this.durable` in the `instance-wrapper.js` file? and try it?

```typescript
isDependencyTreeDurable(lookupRegistry = []) {
        if (!(0, shared_utils_1.isUndefined)(this.isTreeDurable)) {
            return this.isTreeDurable;
        }
        if (this.durable === true) {
            this.isTreeDurable = true;
            this.printIntrospectedAsDurable();
            return this.isTreeDurable;
        }
        const isStatic = this.isDependencyTreeStatic();
        if (isStatic) {
            return false;
        }
        const isTreeNonDurable = this.introspectDepsAttribute((collection, registry) => collection.some((item) => !item.isDependencyTreeStatic() &&
            !item.isDependencyTreeDurable(registry)), lookupRegistry);
        this.isTreeDurable = !isTreeNonDurable && this.durable;   //<--HERE
        if (this.isTreeDurable) {
            this.printIntrospectedAsDurable();
        }
        return this.isTreeDurable;
    }
 ```

**Comment by vizio360** [comment]
@kamilmysliwiec @micalevisk

I think I found the possible problem, at least in our code base it seems to be with pipes as they are marked as `isTreeStatic = true`.
that obviously will return true when calling `isDependencyTreeStatic()` in `instance-wrapper: isDependencyTreeDurable -> introspectDepsAttribute() ` 

Adding `{scope: Scope.REQUEST}` to the Pipe makes it work. 

our controller:
```typescript
    @Get('/ourRoute')
    async ourRoute(
        @Request() req,
        @Query('additionalData', AdditionalDataPipe) additionalData?: AdditionalDataEnum[]
    ): Promise<GetCurrentUserResponse> {
```

The fixed Pipe:
```typescript
@Injectable({
    scope: Scope.REQUEST,
})
export class AdditionalDataPipe implements PipeTransform<string, AdditionalDataEnum[]> {
```

So, not sure if I need to guard against Pipes and treat them differently, I think I need to dig deeper.

**Comment by vizio360** [comment]
and I think I got a test reproducing the issue

```typescript
describe.only('when wrapper is non static and dep is static', () => {
          it('should return false', () => {
            const wrapper = new InstanceWrapper({ scope: Scope.REQUEST });
            wrapper.addCtorMetadata(0, new InstanceWrapper());
            expect(wrapper.isDependencyTreeDurable()).to.be.false;
          });
        });
```

this fails. It should return false.

**Comment by vizio360** [comment]
possible fix in the PR above

**Comment by vizio360** [comment]
nope more investigation needed...

**Comment by vizio360** [comment]
ok got more understanding of the issue, I started commenting on the PR itself.

**Comment by vizio360** [comment]
So I think I got to the bottom of it, and the PR #11041 has been updated. I've also added a diagram to explain the problem.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/11041

**Comment by petrusdemelo** [comment]
Howdy,

I'm facing the same problem with the version 10.3.1

When I add `@Injectable({ scope: Scope.REQUEST, durable: true })` the value in `@Inject(REQUEST) private request: Request`comes undefined.

I tried to track this issue but couldn't find if there was a definitive solution.
