### ISSUE TITLE
GraphQL related build failures after migrating @nestjs/graphql package to v8

### ISSUE THREAD

**Issue by DaniSchenk** [nestjs/nest#7533]
## Regression

Checked migration docs [v7 to v8](https://docs.nestjs.com/migration-guide#nestjsgraphql-package) and GraphQL related module or type errors are not mentioned.

## Potential Commit/PR that introduced the regression**
don't know

## Describe the regression
I tried upgrading `@nestjs/graphql` to v8 and failed. I used the following code to reproduce the issue. Rolling back to `@nestjs/graphql@7` solved my issues.

## Input Code

**Reproduction**:

```bash
npm i -g @nestjs/cli@8
nest new project-name -> choose `npm`
cd project-name
npm run build
```
No failures so far. Now I followed the [GraphQL Quickstart Tutorial](https://docs.nestjs.com/graphql/quick-start)
```bash
npm i @nestjs/graphql graphql-tools graphql apollo-server-express
nest g res example -> choose `GraphQL (code first)`
npm run build
```

I'm receiving the following errors:
```node
> nest build

node_modules/@nestjs/graphql/dist/graphql-ast.explorer.d.ts:2:157 - error TS2307: Cannot find module 'ts-morph' or its corresponding type declarations.

2 import { ClassDeclaration, ClassDeclarationStructure, InterfaceDeclaration, InterfaceDeclarationStructure, ParameterDeclarationStructure, SourceFile } from 'ts-morph';
                                                                                                                                                              ~~~~~~~~~~
node_modules/@nestjs/graphql/dist/graphql-ast.explorer.d.ts:17:192 - error TS2307: Cannot find module 'ts-morph' or its corresponding type declarations.

17     lookupDefinition(item: Readonly<TypeSystemDefinitionNode | TypeSystemExtensionNode>, tsFile: SourceFile, mode: 'class' | 'interface', options: DefinitionsGeneratorOptions): void | import("ts-morph").TypeAliasDeclaration;
                                                                                                                                                                                                  ~~~~~~~~~~
node_modules/@nestjs/graphql/dist/graphql-ast.explorer.d.ts:38:143 - error TS2307: Cannot find module 'ts-morph' or its corresponding type declarations.

38     addEnumDefinition(item: EnumTypeDefinitionNode | EnumTypeExtensionNode, tsFile: SourceFile, options: DefinitionsGeneratorOptions): import("ts-morph").TypeAliasDeclaration;
                                                                                                                                                 ~~~~~~~~~~
node_modules/@nestjs/graphql/dist/interfaces/gql-gateway-module-options.interface.d.ts:1:58 - error TS2307: Cannot find module '@apollo/gateway' or its corresponding type declarations.

1 import { GatewayConfig, ServiceEndpointDefinition } from '@apollo/gateway';
                                                           ~~~~~~~~~~~~~~~~~
node_modules/@nestjs/graphql/dist/interfaces/gql-gateway-module-options.interface.d.ts:2:35 - error TS2307: Cannot find module '@apollo/gateway/dist/datasources/types' or its corresponding type declarations.

2 import { GraphQLDataSource } from '@apollo/gateway/dist/datasources/types';
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 5 error(s).

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-name@0.0.1 build: `nest build`
npm ERR! Exit status 1
```

## Expected behavior/code
I was not expecting module or type declaration errors when migrating from `@nestjs/graphql@7` to `@nestjs/graphql@8`. Neither migration docs nor Nest GraphQL docs mention potential issues or give instructions.

**Nevertheless, rolling back `@nestjs/graphql@7` resolves all build errors.** So the upgrade of `apollo-server-express` package from `2.25.2` to `3.0.0` seems not to be the problem.

## Environment
<pre><code>
Nest version: @nestjs/graphql@7.11.0 -> @nestjs/graphql@8.0.2

For Tooling issues:
- Node version: v14.17.3
- Platform:  Windows

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Duplicate https://github.com/nestjs/graphql/issues/1621
