### ISSUE TITLE
 Error in tests TypeError: this.graphInspector.insertEnhancerMetadataCache is not a function after update to 9

### ISSUE THREAD

**Issue by tttmaximttt** [nestjs/nest#11155]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

8 -> 9

### Describe the regression

` TypeError: this.graphInspector.insertEnhancerMetadataCache is not a function

       6 | export class AppHelper {
       7 |   public async getApp(): Promise<INestApplication> {
    >  8 |     const moduleFixture: TestingModule = await Test.createTestingModule({
         |                                          ^
       9 |       imports: [AppModule]
      10 |     }).compile()
      11 |
`

### Input code

```ts

```

### Expected behavior

no error

**Comment by kamilmysliwiec** [comment]
Make sure `@nestjs/core`, `@nestjs/common`, `@nestjs/testing`, `@nestjs/websockets` and `@nestjs/microservices` are all on the same version
