### ISSUE TITLE
@nestjs/common@5.3.12 breaks @nest-middlewares/express-session@latest

### ISSUE THREAD

**Issue by yuristsepaniuk** [nestjs/nest#1204]
Hello!

Cannot find module '@nestjs/common/interfaces/middlewares/express-midleware.interface'

Everything works fine with @nestjs/common@5.3.11 and @nest-middlewares/express-session@latest.

Should we report issue to @nest-middlewares/express-session?

Thx
-Yura

**Comment by kamilmysliwiec** [comment]
Fixed in 5.3.14

**Comment by yuristsepaniuk** [comment]
@kamilmysliwiec Kamil, sorry, I have the same issue for 5.3.14 version.

Here is my package.json

"dependencies": {
    "@nest-middlewares/express-session": "^5.0.0",
    "@nestjs/common": "^5.0.0",
    "@nestjs/core": "^5.0.0",
    "@nestjs/microservices": "^5.0.0",
    "@nestjs/passport": "^1.0.11",
    "@nestjs/testing": "^5.0.0",
    "@nestjs/websockets": "^5.0.0",
    "busboy": "^0.2.14",
    "class-transformer": "^0.1.9",
    "class-validator": "^0.8.5",
    "connect-mongo": "^2.0.1",
    "dotenv": "^6.0.0",
    "elasticsearch": "^15.1.1",
    "fastify-formbody": "^2.0.0",
    "joi": "^13.4.0",
    "lodash": "^4.17.10",
    "migrate-mongo": "^3.0.3",
    "mongodb": "^3.1.1",
    "mongoose": "^5.1.5",
    "nconf": "^0.10.0",
    "passport": "^0.4.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^6.2.2",
    "stream-json": "^1.1.0"
  },

**Comment by kamilmysliwiec** [comment]
Ahh, misunderstood the issue. Since 5.0.0 we use `MiddlewareFunction` interface instead

**Comment by kamilmysliwiec** [comment]
See migration guide: https://docs.nestjs.com/migration-guide

**Comment by yuristsepaniuk** [comment]
@kamilmysliwiec thx, since we don't use it directly, just FYI, it is referenced from @nest-middlewares/express-session npm package. We will raise new issue there.

// from @nest-middlewares/express-session npm package
import { NestMiddleware } from '@nestjs/common';
import { ExpressMiddleware } from '@nestjs/common/interfaces/middlewares/express-midleware.interface';
import * as expressSession from 'express-session';
export declare class ExpressSessionMiddleware implements NestMiddleware {
    static configure(opts: expressSession.SessionOptions): void;
    private static options;
    resolve(...args: any[]): ExpressMiddleware;
}

**Comment by DelavariMohsen** [comment]
Hi
When i use:
`yarn start:dev` every thing is fine!
But when I debug application with F5 in VS Code i get this error:
`node_modules/@nestjs/testing/testing-module.d.ts:5:41 - error TS2307: Cannot find module '@nestjs/common/interfaces/nest-express-application.interface'.

5 import { INestExpressApplication } from '@nestjs/common/interfaces/nest-express-application.interface';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@nestjs/testing/testing-module.d.ts:6:41 - error TS2307: Cannot find module '@nestjs/common/interfaces/nest-fastify-application.interface'.

6 import { INestFastifyApplication } from '@nestjs/common/interfaces/nest-fastify-application.interface';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@nestjs/testing/testing-module.d.ts:9:32 - error TS2307: Cannot find module '@nestjs/core/adapters/fastify-adapter'.

9 import { FastifyAdapter } from '@nestjs/core/adapters/fastify-adapter';`

But I use express!
thanks.
