### ISSUE TITLE
Custom Decorator Error

### ISSUE THREAD

**Issue by jannomeister** [nestjs/nest#4341]
## Current behavior
When I migrated to v7, I change my custom decorator for getting the `req.user`, I followed the steps from the migration guide, But I'm getting this error `ctx.switchToHttp is not a function` when I make a request to that endpoint with the decorator.

## Input Code

This is my `user.decorator.ts`
```ts
import { createParamDecorator, ExecutionContext } from "@nestjs/common";

export const CurrentUser = createParamDecorator(
  (data: unknown, ctx: ExecutionContext) => {
    console.log("ctx: ", ctx);
    const request = ctx.switchToHttp().getRequest();
    return request.user;
  }
);
```
my user.controller.ts
```ts
import { CurrentUser } from "./user.decorator";
import { User } from "./user.entity";
...
@Get("me")
async getUser(@CurrentUser() user: User) {
  // code here...
}
```

## Expected behavior
it should return the `user` object from `req` object

## Environment

<pre><code>
Nest version: v7.0.0

 
For Tooling issues:
- Node version: v10.16.3  
- Platform: Mac

**Comment by kamilmysliwiec** [comment]
I've just tested this code locally and it works fine. Are you sure that you updated all packages? `@nestjs/core`, `@nestjs/common`, etc? You can also try removing `node_modules` and reinstalling all of them.

**Comment by jannomeister** [comment]
@kamilmysliwiec yeah. I update all my nestjs related dependencies and remove the `node_modules` and `npm install`. Still getting the error. Btw, I used `nest update` to update my dependencies.

<img width="395" alt="Screen Shot 2020-03-18 at 3 35 36 PM" src="https://user-images.githubusercontent.com/46916819/76936573-1df18100-692e-11ea-9e15-0a81985bf64c.png">

**Comment by kamilmysliwiec** [comment]
All packages are v6 here, not v7.

**Comment by jannomeister** [comment]
I forgot to use `--force` in my `nest update` to upgrade to the next version and not only update it. After I upgraded all the dependencies it all work fine :) closing this one
