### ISSUE TITLE
strongly-typed decorators: infer return type of transform prop

### ISSUE THREAD

**Issue by elijaholmos** [nestjs/nest#12264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The strongly-typed decorator factories introduced in #12237 are really cool. Thanks for adding them.

I noticed a small problem that comes up with a slightly advanced usage. Currently, the return type of `Refector.get(ReflectableDecorator<T>)` is typed as whatever `ReflectableDecorator<T>` was initialized as, using `Reflector.createDecorator`. This is great for simple metadata storage, but if the `transform` method is used to alter the input value before it is stored, the return type does not update to match the `transform` method's return type.

As an example:
```ts
// roles.decorator.ts
import { Reflector } from '@nestjs/core';

export const Roles = Reflector.createDecorator<string | string[]>({
  key: 'roles',
  transform: (...roles: string[]): string[] => roles ?? [],
});
```

```ts
// decorator usage
import { Roles } from './roles.decorator';
@Roles('admin')
```

```ts
// roles.guard.ts
import { CanActivate, ExecutionContext, Injectable } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { Roles } from './roles.decorator';

@Injectable()
export class PolicyGuard implements CanActivate {
  constructor(protected readonly reflector: Reflector) {}

  canActivate(context: ExecutionContext): boolean {
    const roles = this.reflector.get(Roles, context.getHandler()) || [];

    return roles.some((role) => role === 'admin'); // TypeError: Property 'some' does not exist on type 'string | string[]'.
  }
}
```

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-yoxyxj?file=src%2Froles.guard.ts

### Expected behavior

Ideally, the typing system would be able to detect the return value on the `transform` property, and use that as the return value of the `Refector.get(ReflectableDecorator<T>)` method. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.2.1

### Packages versions

[System Information]
OS Version     : Windows 10
NodeJS Version : v18.16.0
PNPM Version    : 8.6.12 

[Nest CLI]
Nest CLI Version : 10.1.12

[Nest Platform Information]
platform-express version : 10.2.1
mapped-types version     : 2.0.2
schematics version       : 10.0.2
passport version         : 10.0.1
graphql version          : 12.0.8
testing version          : 10.2.1
apollo version           : 12.0.7
common version           : 10.2.1
config version           : 3.0.0
core version             : 10.2.1
jwt version              : 10.1.0
cli version              : 10.1.12

### Node.js version

18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
```
transform: (...roles: string[]): string[] => roles ?? [],
```

should be

```
transform: (...roles: string | string[]): string[] => ...,
```

than you probably won't get that error at runtime anymore.

Not sure if we can enforce that as you've declared at type explicitly...

**Comment by micalevisk** [comment]
another thing that we could improve (not sure if it's feasible):

```
transform: (...roles: string[]): string[] => roles ?? []
```

this should error out at compiler time because of    
`Reflector.createDecorator<string | string[]>`

that `roles` parameter will be `string[][]` when using `@Roles(['foo'])`. And it will be `string[]` when using `@Roles('foo')`

**Comment by quangtran88** [comment]
I think we can add a second optional generic param on Reflector.createDecorator to describe the transformed value type as following:
```
const Roles = Reflector.createDecorator<string | string[], string[]>({
  key: 'roles',
  transform: (...roles: string[]): string[] => roles ?? [], // Must return type string[]
});
```

**Comment by micalevisk** [comment]
yeah, that should work. I just made a PoC

![image](https://github.com/nestjs/nest/assets/13461315/09c1b9a6-f6e4-4e7f-869f-4c5cc4a47081)

**Comment by quangtran88** [comment]
I created a PR https://github.com/nestjs/nest/pull/12276 for this.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/12276
