### ISSUE TITLE
Fastify v3 support

### ISSUE THREAD

**Issue by numToStr** [nestjs/nest#5055]
## What is the motivation / use case for changing the behavior?
Fastify v3 release: https://github.com/fastify/fastify/releases/tag/v3.0.0

**Comment by Green-Cat** [comment]
This should take too much work. There aren't many breaking changes in fastify 3. I'll try my hand at a PR if no one else does by this weekend.

**Comment by AcidSlide** [comment]
I hope this does get updated, updating components that are fastify based like fastify-swagger and fastify-multipart gets broken since it requires Fastify v3.

**Comment by hongyiweiwu** [comment]
I can make a try tonight. Doesn't seem like too much work.

**Comment by hongyiweiwu** [comment]
#5070

**Comment by StevenLangbroek** [comment]
What's maybe worth mentioning is that there's an issue in `apollo-server-fastify`, making GraphQL Playground never work: https://github.com/apollographql/apollo-server/issues/4122. I'd started working on a fix but tbh for our use (_just_ fastify & graphql, sans NestJS) `fastify-gql` is probably a better fit.

**Comment by kamilmysliwiec** [comment]
Still waiting for https://github.com/apollographql/apollo-server/issues/4355

**Comment by kamilmysliwiec** [comment]
7.4.0 is compatible with 3.0.0 now

**Comment by AcidSlide** [comment]
Hello, after updating to 7.4.0 we got this error

```
node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.d.ts:10:36 - error TS2307: Cannot find module 'point-of-view' or its corresponding type declarations.

10 import { PointOfViewOptions } from 'point-of-view';
                                      ~~~~~~~~~~~~~~~

```

**Comment by jmcdo29** [comment]
I can confirm on a fresh nest project using fastify, the application is not able to start without installing `point-of-view` and `fastify-static`. For now as a workaround you can either downgrade to 7.3.x or you can install these two packages.

**Comment by kamilmysliwiec** [comment]
Thanks for reporting @AcidSlide @jmcdo29. It should be fixed in 7.4.1

**Comment by jmcdo29** [comment]
Works great! Thanks for the quick fix

**Comment by AcidSlide** [comment]
Hi @kamilmysliwiec still broken for me in 7.4.1.. the Fastify Options doesn't work anymore, i've tried even the most basic options which is enabling the logger (as based on https://docs.nestjs.com/techniques/performance#fastify-options)

```
src/main.ts:57:24 - error TS2345: Argument of type '{ logger: true; }' is not assignable to parameter of type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance> | FastifyHttp2Options<...>'.
  Type '{ logger: true; }' is not assignable to type 'FastifyHttp2Options<Server, FastifyLoggerInstance>'.
    Property 'http2' is missing in type '{ logger: true; }' but required in type '{ http2: true; http2SessionTimeout?: number; }'.

57     new FastifyAdapter({
                          ~
58       logger: true,
   ~~~~~~~~~~~~~~~~~~~
59     }),
   ~~~~~

  node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.d.ts:15:5
    15     http2: true;
           ~~~~~
    'http2' is declared here.

Found 1 error(s).
```

**Comment by kamilmysliwiec** [comment]
Fixed in 7.4.2

**Comment by AcidSlide** [comment]
Thanks @kamilmysliwiec confirming it works.. now I just need to find a way to make fastify-multipart work ahahaha

**Comment by AcidSlide** [comment]
Hmmm.. it looks like we can't register the fastify-multipart plugin with the FastifyAdaptor anymore (https://github.com/fastify/fastify-multipart using also this docs https://dev.to/sergey_telpuk/nestjs-fastify-multer-uploading-cropping-image-12b9 and https://medium.com/@427anuragsharma/upload-files-using-multipart-with-fastify-and-nestjs-3f74aafef331)

**Comment by newcoder171** [comment]
Hi @kamilmysliwiec, I just created a new nest project and in trying to use fastify without any options but I get this message 

`node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.d.ts:50:5 - error TS2416: Property 'createMiddlewareFactory' in type 'FastifyAdapter<TServer, TRawRequest, TRawResponse>' is not assignable to the same property in base type 'AbstractHttpAdapter<TServer, FastifyRequest<RequestGenericInterface, TServer, TRawRequest>, FastifyReply<TServer, TRawRequest, TRawResponse, RouteGenericInterface, unknown>>'.
  Type '(requestMethod: RequestMethod) => Promise<(path: string, callback: Function) => any>' is not assignable to type '(requestMethod: RequestMethod) => (path: string, callback: Function) => any'.
    Type 'Promise<(path: string, callback: Function) => any>' is not assignable to type '(path: string, callback: Function) => any'.

50     createMiddlewareFactory(requestMethod: RequestMethod): Promise<(path: string, callback: Function) => any>;
       ~~~~~~~~~~~~~~~~~~~~~~~
src/main.ts:11:5 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(module: any, options?: NestApplicationOptions): Promise<NestFastifyApplication>', gave the following error.
    Type 'FastifyAdapter<Server, IncomingMessage, ServerResponse>' has no properties in common with type 'NestApplicationOptions'.
  Overload 2 of 2, '(module: any, httpAdapter: AbstractHttpAdapter<any, any, any>, options?: NestApplicationOptions): Promise<NestFastifyApplication>', gave the following error.
    Argument of type 'FastifyAdapter<Server, IncomingMessage, ServerResponse>' is not assignable to parameter of type 'AbstractHttpAdapter<any, any, any>'.
      The types returned by 'createMiddlewareFactory(...)' are incompatible between these types.
        Type 'Promise<(path: string, callback: Function) => any>' is not assignable to type '(path: string, callback: Function) => any'.
          Type 'Promise<(path: string, callback: Function) => any>' provides no match for the signature '(path: string, callback: Function): any'.

11     new FastifyAdapter(),
       ~~~~~~~~~~~~~~~~~~~~


Found 2 error(s).`

**Comment by kamilmysliwiec** [comment]
@newcoder171 make sure to keep `@nestjs/core`, `@nestjs/common` and `@nestjs/platform-fastify` versions in sync (for example, 7.4.1)

**Comment by newcoder171** [comment]
@kamilmysliwiec thanks. everything works fine now

**Comment by coderdiaz** [comment]
@kamilmysliwiec what version of `apollo-server-fastify` works?

**Comment by jmcdo29** [comment]
`apollo-server-fastify@3.0.0-alpha.3`

**Comment by mubaidr** [comment]
Any update on this issue? `apollo-server-fastify@3.0.0-alpha4` has breaking changes and does not work any more.

**Comment by batflarrow** [comment]
> @newcoder171 make sure to keep `@nestjs/core`, `@nestjs/common` and `@nestjs/platform-fastify` versions in sync (for example, 7.4.1)
@kamilmysliwiec 
Should we still follow this guideline when upgrading v9? I am currently trying to resolve the fastify [security vulnerability ](https://security.snyk.io/vuln/SNYK-JS-FASTIFY-3136527) and I am forced to upgrade @nestjs/platform-fastify to V9 because fastify was upgraded to a non-vulnerable version in nest v9 but our current nest version is v8 and we don't want to upgrade to v9 just yet, is there any way I can resolve the vulnerability and still remain on the same version?
