### ISSUE TITLE
v8: CacheModule is not working: Cannot read property 'httpAdapter' of undefined

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#7168]
## Current behavior
Importing `CacheModule.register()` and then using `@UseInterceptors(CacheInterceptor)` throws an error:

> Cannot read property 'httpAdapter' of undefined

When downgrading to 7.x it works as expected.

Repo: https://github.com/MickL/nestjs-8-cache-bug

Reproduce:

1. yarn start
2. curl localhost:3000

## Environment

<pre><code>
Nest version: 8.0.0-alpha.4
 
For Tooling issues:
- Node version: v14.17.0
- Platform: macOS Big Sur
</code></pre>

**Comment by jmcdo29** [comment]
I believe this is because in v8 the injection tokens are set by instance rather than by string. Nest is [using the string name of the `HttpAdapterHost`](https://github.com/nestjs/nest/blob/8.0.0/packages/common/cache/interceptors/cache.interceptor.ts#L17) to keep from having a circular dependency back on `@nestjs/core`.

**Comment by kamilmysliwiec** [comment]
Fixed in 8.0.0-alpha.5. Thanks for reporting!

**Comment by MickL** [comment]
@kamilmysliwiec There is another error now in alpha5:

> TypeError: rxjs_1.lastValueFrom is not a function
>     at RouterResponseController.transformToResult (/Users/mick/Documents/Git/nestjs-8-cache-bug/node_modules/@nestjs/core/router/router-response-controller.js:32:27)

Updated my repo. Please reopen :)

**Comment by kamilmysliwiec** [comment]
Make sure to update to the latest rxjs version (I'll update docs to mention that as well)

**Comment by MickL** [comment]
Thanks for the fast reply, works now!

**Comment by mjgp2** [comment]
I am still seeing the `rxjs_1.lastValueFrom` not being defined bug in alpha 7 @kamilmysliwiec 

It looks like this was introduced in rxjs7 but all the package.json dependencies are still 6.x?

**Comment by cdoukoure** [comment]
Hi everyone.

After upgrade to v8 i always get this error even if i uninstall the nestjs/cqrs package

> Nest can't resolve dependencies of the CommandBus (?). Please make sure that 
> the argument ModuleRef at index [0] is available in the CqrsModule context.
