### ISSUE TITLE
cookie-parser does not work with default nestjs@10.0.0 template

### ISSUE THREAD

**Issue by wavedeck** [nestjs/nest#11991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have followed the docs on [cookies in nestjs](https://docs.nestjs.com/techniques/cookies) and upon running the project, the server crashed with an error.

it seems as if the default import syntax is the culprit because using a wildcard import works fine. 
This issue is also resolved by setting `esModuleInterop: true` in tsconfig.json

### Minimum reproduction code

https://github.com/wavedeck/nestjs-cookieparser-issue

### Steps to reproduce

1. Install cookie-parser and @types/cookie-parser
2. register the cookieParser middleware on the express app instance like this (following the docs)
```js
// ...other imports
import cookieParser from 'cookie-parser';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.use(cookieParser());
  await app.listen(8080);
}
bootstrap();
```
3. Observe the server crashing upon first request
```
/Users/davidfally/dev/projects/app/src/main.ts:8
  app.use(cookieParser());
                      ^
TypeError: (0 , cookie_parser_1.default) is not a function
    at bootstrap (/Users/davidfally/dev/projects/app/src/main.ts:8:23)
```

4. Change the import to a wildcard
```js
import cookieParser from 'cookie-parser'; // remove this
import * as cookieParser from 'cookie-parser'; // add this -> works
```

### Expected behavior

Following the official docs should result in a functioning application.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

cookie-parser

### NestJS version

10.0.0

### Packages versions

```json
{
  "name": "app",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "cookie-parser": "^1.4.6",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/cookie-parser": "^1.4.3",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0",
    "prettier": "^2.8.8",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

v20.3.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Interesting that that's how our docs are. [Cookie parser is not a default export](https://github.com/expressjs/cookie-parser/blob/master/index.js#L23) so it should be expected to have to `import * as cookieParser from 'cookie-parser';` unless you do set `esModuleInterop: true`.

**Comment by micalevisk** [comment]
https://github.com/nestjs/docs.nestjs.com/pull/2786

![image](https://github.com/nestjs/nest/assets/13461315/8a7ec8c4-2742-4880-a60f-67830194d48c)
