### ISSUE TITLE
[Bug report] TypeError: instance.onApplicationBootstrap is not a function

### ISSUE THREAD

**Issue by joker-dev** [nestjs/nest#1047]
## When I use version:5.1.0 it is okey, but it is not work in version:5.3.2 o(╯□╰)o   

<pre><code>
(node:10892) UnhandledPromiseRejectionWarning: TypeError: instance.onApplicationBootstrap is not a function
    at MapIterator.Promise.all.iterare_1.default.map.filter.filter.map [as iteratee] (/Users/joker/Repository/blockChain/site-center/node_modules/@nestjs/core/nest-application-context.js:111:53)
    at MapIterator.next (/Users/joker/Repository/blockChain/site-center/node_modules/iterare/lib/map.js:13:39)
    at IteratorWithOperators.next (/Users/joker/Repository/blockChain/site-center/node_modules/iterare/lib/iterate.js:21:28)
    at Function.all (<anonymous>)
    at NestApplication.callModuleBootstrapHook (/Users/joker/Repository/blockChain/site-center/node_modules/@nestjs/core/nest-application-context.js:107:23)
    at NestApplication.callBootstrapHook (/Users/joker/Repository/blockChain/site-center/node_modules/@nestjs/core/nest-application-context.js:100:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
(node:10892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:10892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</code></pre>

## Environment

<pre><code>
Nest version: 5.3.2

 
For Tooling issues:
- Node version: v8.11.3  
- Platform: Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 5.3.3
