### ISSUE TITLE
TypeError: instance.getTimestamp is not a function

### ISSUE THREAD

**Issue by mcarlotta** [nestjs/nest#6175]
## Bug Report
Ever since upgrading to 7.6, this error occurs forcing me to lock version to 7.5.5. 

I am wanting to invoke my own custom logger and following documentation which references to setting logger to false when wanting to do so

## Current behavior
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[0] TypeError: instance.getTimestamp is not a function
[0]     at Function.printMessage (/.../node_modules/@nestjs/common/services/logger.service.js:100:58)
[0]     at Function.log (/.../node_modules/@nestjs/common/services/logger.service.js:49:14)
[0]     at SentryLogger.log (/.../dist/server/src/logger/logger.service.js:49:25)
[0]     at Logger.callFunction (/.../node_modules/@nestjs/common/services/logger.service.js:82:18)
[0]     at Logger.log (/.../node_modules/@nestjs/common/services/logger.service.js:24:14)
[0]     at /.../node_modules/@nestjs/core/router/routes-resolver.js:37:25
[0]     at Map.forEach (<anonymous>)
[0]     at RoutesResolver.registerRouters (/.../node_modules/@nestjs/core/router/routes-resolver.js:32:16)
[0]     at /.../node_modules/@nestjs/core/router/routes-resolver.js:28:18
[0]     at Map.forEach (<anonymous>)

## Input Code

```ts
  const app = await NestFactory.create(AppModule, {
    logger: false,
  })

  const configService = app.get(ConfigService)
  const sentryLogger = app.get(SentryLogger)

  app.enableCors()
  app.useLogger(app.get(SentryLogger))
  app.useGlobalFilters(new AllExceptionsFilter(sentryLogger))
  app.useGlobalPipes(new ValidationPipe())

```

## Expected behavior
App loads successfully 

## Environment

<pre><code>
Nest version:7.6.5

 
For Tooling issues:
- Node version: v14.12.0
- Platform:  MAc

Others:

</code></pre>

**Comment by chaos-sl** [comment]
I got this error too. 
But I noticed that some module use Logger.log() directly in Service constructor when module initializing...
So delete Logger.log in constructor Or change to new Logger().log .
Solved...
```
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlicloudOssService = void 0;
const common_1 = require("@nestjs/common");
const OSS = require("ali-oss");
const alicloud_oss_constant_1 = require("./alicloud-oss.constant");
let AlicloudOssService = class AlicloudOssService {
    constructor(config) {
        this.config = config;
        this.clients = {};
        this.clients[config.options.bucket] = new OSS(config.options);
        this.defaultClient = this.clients[config.options.bucket];

       // Error
         common_1.Logger.log('Alicloud OSS module initialized!', 'AlicloudOssModule');
      // OK
         new common_1.Logger().log('Alicloud OSS module initialized!', 'AlicloudOssModule');
    }
   ......
```

**Comment by Tony133** [comment]
Hi @mcarlotta you can leave a minimal reproduction of a clonable git repo so the core team can evaluate the problem you reported.

**Comment by kamilmysliwiec** [comment]
I've seen this error before and we fixed it already in one of the recent releases. Update your `@nestjs/` packages and make sure both `@nestjs/common` and `@nestjs/core` packages are in sync.

**Comment by jeiea** [comment]
`npm audit fix` may be a culprit.

**Comment by Erchoc** [comment]
today i update yarn.lock, seem the same problem. all nestjs dependencies is 7.6.5

**Comment by Erchoc** [comment]
![image](https://user-images.githubusercontent.com/19908809/105122992-3ca64280-5b12-11eb-8588-5af596c9687f.png)

![image](https://user-images.githubusercontent.com/19908809/105123072-62334c00-5b12-11eb-8af9-f68e364551db.png)

@kamilmysliwiec

**Comment by jmcdo29** [comment]
@Erchoc are you able to provide a minimum reproduction?

**Comment by kylecannon** [comment]
I am experiencing this issue as well. This seems to be related when you do 

`app.useLogger(app.get(MyGenericLogger));`

**Comment by kylecannon** [comment]
My initial investigation has to do with the fact that when you use `app.useLogger(app.get(MyCustomLogger));`

**Comment by mcarlotta** [comment]
> My initial investigation has to do with the fact that when you use `app.useLogger(app.get(MyCustomLogger));`

This is how documentation suggests configuration. The setup has worked up until 7.6 release. 

Currently on 7.5.5 and works as expected

```
https://docs.nestjs.com/techniques/logger#logger

const app = await NestFactory.create(ApplicationModule, {
  logger: false,
});
app.useLogger(app.get(MyLogger));
await app.listen(3000);

```

**Comment by mcarlotta** [comment]
> I've seen this error before and we fixed it already in one of the recent releases. Update your `@nestjs/` packages and make sure both `@nestjs/common` and `@nestjs/core` packages are in sync.

Updated all core packages and still issue persists

Package
```
...
"dependencies": {
    "@nestjs/common": "^7.6.5",
    "@nestjs/config": "^0.6.2",
    "@nestjs/core": "^7.6.5",
    "@nestjs/jwt": "^7.2.0",
    "@nestjs/microservices": "^7.6.5",
    "@nestjs/platform-express": "^7.6.5",
    "@sentry/node": "^5.30.0",
    "@sentry/tracing": "^5.30.0",
    "amqp-connection-manager": "^3.2.1",
    "amqplib": "^0.6.0",
    "bcrypt": "^5.0.0",
    "boolean": "^3.0.2",
    "chalk": "^4.1.0",
    "class-transformer": "^0.3.2",
    "class-validator": "^0.12.2",
    "faker": "^5.2.0",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "pg": "^8.5.1",
    "pg-hstore": "^2.3.3",
    "random": "^2.2.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.3",
    "sequelize": "^5.22.3",
    "sequelize-paginate": "^1.1.6",
    "sequelize-typescript": "^1.1.0",
    "shortid": "^2.2.16",
    "umzug": "^2.3.0",
    "uuid": "^8.3.2",
    "uuid-token-generator": "^1.0.0"
  }
  ...
````

**Comment by jmcdo29** [comment]
> > I've seen this error before and we fixed it already in one of the recent releases. Update your `@nestjs/` packages and make sure both `@nestjs/common` and `@nestjs/core` packages are in sync.
> 
> Updated all core packages and still issue persists
> 
> Package
> 
> ```
> ...
> "dependencies": {
>     "@nestjs/common": "^7.6.5",
>     "@nestjs/config": "^0.6.2",
>     "@nestjs/core": "^7.6.5",
>     "@nestjs/jwt": "^7.2.0",
>     "@nestjs/microservices": "^7.6.5",
>     "@nestjs/platform-express": "^7.6.5",
>     "@sentry/node": "^5.30.0",
>     "@sentry/tracing": "^5.30.0",
>     "amqp-connection-manager": "^3.2.1",
>     "amqplib": "^0.6.0",
>     "bcrypt": "^5.0.0",
>     "boolean": "^3.0.2",
>     "chalk": "^4.1.0",
>     "class-transformer": "^0.3.2",
>     "class-validator": "^0.12.2",
>     "faker": "^5.2.0",
>     "lodash": "^4.17.20",
>     "moment": "^2.29.1",
>     "pg": "^8.5.1",
>     "pg-hstore": "^2.3.3",
>     "random": "^2.2.0",
>     "reflect-metadata": "^0.1.13",
>     "rimraf": "^3.0.2",
>     "rxjs": "^6.6.3",
>     "sequelize": "^5.22.3",
>     "sequelize-paginate": "^1.1.6",
>     "sequelize-typescript": "^1.1.0",
>     "shortid": "^2.2.16",
>     "umzug": "^2.3.0",
>     "uuid": "^8.3.2",
>     "uuid-token-generator": "^1.0.0"
>   }
>   ...
> ```

Do you have a [minimum reproduction](http://minimum-reproduction.wtf) available showing this same issue?

**Comment by mcarlotta** [comment]
After setting up a bare NestJS app, I am thinking there is some sort of dependency conflict in my application

As stated, NestJS 7.5.5 works fine but something in 7.6 is a breaking change for me resulting in

```
const computedMessage = `${pidMessage}${instance.getTimestamp()}   ${contextMessage}${output}${timestampDiff}\n`;
                                                         ^

TypeError: instance.getTimestamp is not a function
```

**Comment by jmcdo29** [comment]
If you can provide a reproduction, or access to what's reproducing this, I'll look into it. Otherwise, there's not much we can do

**Comment by mcarlotta** [comment]
> If you can provide a reproduction, or access to what's reproducing this, I'll look into it. Otherwise, there's not much we can do

Working on stripping down app to set something up

**Comment by kamilmysliwiec** [comment]
Please, test with `@nestjs/common@7.6.6`

**Comment by kylecannon** [comment]
That works, except when you use the original logger after you override it, you get `[Nest] 9143   - undefined   Listening at http://localhost:3333 +1001ms`, missing the date. 

It doesn't crash anymore though. 👍
