### ISSUE TITLE
Build Fails After Upgrading Microservices to >=6.4.1

### ISSUE THREAD

**Issue by mkaufmaner** [nestjs/nest#2534]
## Current behavior
The nestjs project fails to build after upgrading `@nestjs/microservices` dependency to 6.4.1 from 6.4.0.  This problem still exists with 6.5.0

## Input Code
```sh
> rimraf dist && tsc -p tsconfig.build.json

node_modules/@nestjs/microservices/external/redis.interface.d.ts:2:23 - error TS2688: Cannot find type definition file for 'mocha'.

2 /// <reference types="mocha" />
```

## Expected behavior

To complete building without error.

## Possible Solution
There was a regression between v6.4.0 and v6.4.1.  Either way, the reference to mocha in `redis.interface.d.ts` needs to be removed.  I am not sure why it is there.

```ts
/// <reference types="node" />
/// <reference types="mocha" />
export interface RetryStrategyOptions {
    error: Error;
    total_retry_time: number;
    times_connected: number;
    attempt: number;
}
```

## Environment

<pre><code>
Nest version: >=6.4.1 and 6.5.0
 
For Tooling issues:
- Node version: v10.15.0
- Platform:  Mac & Linux

Others:

</code></pre>

**Comment by dantehemerson** [comment]
Yes i have the same issue.

**Comment by csidell-earny** [comment]
I took a look at the file and I don't know why it even has mocha in there? @kamilmysliwiec Do you have an idea?

**Comment by dynamikus** [comment]
That is not something that @kamilmysliwiec is doing. (https://github.com/nestjs/nest/blob/master/packages/microservices/external/redis.interface.ts).
It is more Typescript compiler getting confused and assuming redis.interface.ts need a reference to mocha types.

**Comment by csidell-earny** [comment]
@dynamikus I didn't think he was behind it in the first place, but I thought he might have some insight into a potential reason as to why this reference suddenly just showed up.

Doing some additional digging I have seen the `NodeJS` namespace thing around and haven't relied on it. Unfortunately it seems that mocha decided to forward declare the NodeJS.EventEmitter namespace here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mocha/index.d.ts#L2793

**Comment by dantehemerson** [comment]
Just to add something. 
I compile with v6.4.0 and the line `/// <reference types="mocha" />
`  is not added but with v6.4.1 it is added.
We must track the changes in dependencies.

**Comment by csidell-earny** [comment]
The weird thing about that is that definition has been there for at least a year. My guess is that at some point tsc changed to finding references alphabetically since mocha > node. 

However that's a complete guess.

**Comment by kamilmysliwiec** [comment]
Fixed in 6.5.1 :)
