### ISSUE TITLE
@nestjs/platform-fastify 7.4 is a breaking change

### ISSUE THREAD

**Issue by jaybhub** [nestjs/nest#5171]
## Current behavior
7.2.x requires fastify 2.x.
7.4.x requires fastify 3.x.
Using 7.4x is breaking projects with fastify 2.x dependencies

```ts
const serverOptions: fastify.ServerOptionsAsHttp = {
    logger: ['log', 'error', 'warn'],
  };
```
throws error:  Namespace '"<relative path>/node_modules/fastify/fastify"' has no exported member 'ServerOptionsAsHttp'. ts(2694) [90, 32]

```ts
const instance: fastify.FastifyInstance = fastify(serverOptions);
```
throws error:  This expression is not callable.
  Type 'typeof import("<relative path>/node_modules/fastify/fastify")' has no call signatures.

## Input Code
```ts
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';
import * as fastify from '../node_modules/fastify';

let fastifyServer: fastify.FastifyInstance;

async function bootstrap(): Promise<fastify.FastifyInstance> {
  const serverOptions: fastify.ServerOptionsAsHttp = {
    logger: ['log', 'error', 'warn'],
  };
  const instance: fastify.FastifyInstance = fastify(serverOptions);
  const nestApp = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(instance),
    {
      logger: ['log', 'error', 'warn'],
    },
  );
```

## Expected behavior
Minor increments are non-breaking

## Possible Solution
7.4 should be 8.x

## Environment

<pre><code>
Nest version: 6.14.1

 
For Tooling issues:
- Node version: 12.13.0
- Platform:  Mac

Others:
Using npm and VSCode
</code></pre>

**Comment by cazlu8** [comment]
I am getting this error:  UnhandledPromiseRejectionWarning: TypeError: reply_1.Reply is not a constructor
with this same versions.

**Comment by cazlu8** [comment]
same here, is breaking the Exception filters.

**Comment by camo-f** [comment]
It is also a breaking change for projects using GraphQL with Fastify, as `apollo-server-fastify` does not support Fastify 3.x for now.

**Comment by coderdiaz** [comment]
@camo-f I have the same problem with GraphQL using Fastify with `apollo-server-fastify`.

**Comment by robinsmedberg** [comment]
I have the same problem with GraphQL using Fastify with apollo-server-fastify

**Comment by coderdiaz** [comment]
@robinsmedberg Check it out. I'm waiting too for the update from `apollo-server-fastify` for upgrade to Fastify v3. This is in alpha now. 

https://github.com/nestjs/nest/issues/5055#issuecomment-696982213

**Comment by cyb3rs4pi3n** [comment]
works fine in `"@nestjs/common": "^7.5.2" , "@nestjs/platform-fastify": "^7.5.2",`

**Comment by camo-f** [comment]
Also works fine for GraphQL with the following versions
```
"@nestjs/common": "^7.5.5",
"@nestjs/core": "^7.5.5",
"@nestjs/graphql": "^7.8.2",
"@nestjs/platform-fastify": "^7.5.5",
"apollo-server-fastify": "^2.19.0"
```

**Comment by SalahAdDin** [comment]
any solution here?

**Comment by MeStrak** [comment]
A very recent comment on the v3 roadmap issue in the Apollo Server repo looks like things are progressing, but it also seems lime it won't be a transparent upgrade: https://github.com/apollographql/apollo-server/issues/2360#issuecomment-803149134

**Comment by NickMandylas** [comment]
> any solution here?

This version (https://github.com/autotelic/apollo-server-fastify) is maintained/updated & works with Fastify v3.

**Comment by SalahAdDin** [comment]
> > any solution here?
> 
> This version (https://github.com/autotelic/apollo-server-fastify) is maintained/updated & works with Fastify v3.

It is not an official one, isn't it?

**Comment by NickMandylas** [comment]
> > > any solution here?
> > 
> > 
> > This version (https://github.com/autotelic/apollo-server-fastify) is maintained/updated & works with Fastify v3.
> 
> It is not an official one, isn't it?

It's not official, but works perfectly fine.

**Comment by kuongknight** [comment]
apollo-server-fastify@3.0.0-alpha.3 didn't not work with installSubscriptionHandlers option.
Error: `TypeError: this.apolloServer.installSubscriptionHandlers is not a function`

**Comment by tkow** [comment]
I found sometimes library missed fixed version. If you only install apollo-server-fastify@3.0.0-alpha.x and haven't had lock set alpha version, it might break now.
https://github.com/apollographql/apollo-server/issues/5278
